### PR TITLE
Add "label_area" attribute to classification.geojson

### PR DESCRIPTION
**Pull request by wouellette**
On top of the "label" attribute indicating the presence or absence of a given class in the classification.geojson output, a new attribute called "label_area" was integrated which indicates the surface area of the present classes in a given tile. This is particularly useful as an indicator of class abundance.

### CODE REVIEW

**Comment by drewbo** [comment]
@wouellette can you describe the use case here (and could it also be accomplished by using segmentation labels)?

**Comment by wouellette** [comment]
Hi Drew, 

I use the label-maker to filter on the following classes:
```
  "classes": [
	{ "name": "Woody", "filter": ["any", ["in","natural","wood"], ["in","landuse","forest"]] },
	{ "name": "Herbaceous", "filter": ["all",["any", ["in","natural","grassland"], ["in","landuse","grass"],["in","surface","grass"]],["!has", "highway"]] },
	{ "name": "Cropland", "filter": ["in","landuse","farmland"] },
	{ "name": "Bare Soil", "filter": ["in","natural","scree","bare_rock","shingle"] },
	{ "name": "Sand", "filter": ["all",["any", ["in","natural","beach","sand"], ["in","surface","sand"]],["!has", "highway"]] },
	{ "name": "Built-Up", "filter": ["all",["any", ["in","landuse","residential","commercial","industrial","retail"], ["in","surface","paved","asphalt","concrete"]],["!has", "highway"]] },
    	{ "name": "Permanent Water", "filter": ["any", ["in","natural","water"], ["in","water","pond","lake","reservoir"]] },
	{ "name": "Intermittent Water", "filter": ["any", ["in","water","intermittent"], ["in", "natural", "wetland"]] },
	{ "name": "Ice and Snow", "filter": ["in","natural","glacier"] }

```

And for me, knowing absence/presence of the feature per zoom level tile is not enough, I also want to know the abundance. The idea is that OSM QA tiles containing the largest surfaces areas of the above mapped classes are higher priority tiles to be used for training. 

I was initially using a postgis load of OSM to do this, but using the OSM QA tile set is much more efficient, and the label-maker interface to those tiles works wonderfully well for me.

Moreover, since OSM data is often not good enough for training models due to its inaccuracy/inconsistency, tiles with higher class abundances are more likely to contain the features of interest, and therefore a subset of the generated tiles containing the classes of interest in "large" amounts could be revised/realigned (in the case of segmentation) or simply moderated (in the case of classification).

I am not currently using the label-maker further than the `download` and `labels` functionalities, because I use the `classification.geojson` output as part of another process which does pretty much what I describe above. My fork of the label-maker has this implemented for the classification, but the exact same thing could be done for the segmentation procedure (and would probably be even more relevant for that case).

**Comment by drewbo** [comment]
Sounds great @wouellette.  Can you update the test fixtures so that this passes and then I'll merge? Let me know if you need any help with that

**Comment by wouellette** [comment]
Closing it as this pull request has been taken up into https://github.com/developmentseed/label-maker/pull/135

**Pull request closed without merging**
