### PR TITLE
fix image and tile format inconsistency

### PR DESCRIPTION
**Pull request by giswqs**
When a local GeoTIFF or a remote Cloud Optimized GeoTIFF is provided, the image tiles are generated in jpg format. Therefore, the `label-maker package` command should look for image tiles in jpg format rather than tif format.

### CODE REVIEW

**Comment by giswqs** [comment]
@drewbo Thanks a lot for adding support for GeoTIFF reading!! I tested the new version using a local GeoTIFF, everything worked fine except the `package` command, which was looking for *.tif in the tiles folder. However, the titles were generated using jpg format earlier. Therefore, no tif tiles could be found and the resulting `data.npz` is empty.  I added two lines. Now everything works like a charm! Thanks a lot for such a great tool!

**Comment by drewbo** [comment]
Thanks @giswqs we definitely overlooked this. Could you add a test case for this situation to [test/integration](https://github.com/developmentseed/label-maker/tree/master/test/integration) folder? I can give some assistance setting that up if you need

**Comment by giswqs** [comment]
@drewbo This is my first-time learning and using unittest. Feel free to discard my changes if it is the not right way. Added files:

- [test/fixtures/integration/config.intergration.geotiff_package.json](https://github.com/giswqs/label-maker/blob/master/test/fixtures/integration/config.intergration.geotiff_package.json)

- [test/integration/test_geotiff_package.py](https://github.com/giswqs/label-maker/blob/master/test/integration/test_geotiff_package.py)

What I did:

- Downloaded a sample GeoTIFF from [here](http://oin-hotosm.s3.amazonaws.com/593ede5ee407d70011386139/0/3041615b-2bdb-40c5-b834-36f580baca29.tif) and saved it to [test/fixtures/integration/geotiff/](https://github.com/giswqs/label-maker/tree/master/test/fixtures/integration/geotiff)

- Run the following three commands. The resulting files are saved to the folder `sao_tome` under [test/fixtures/integration/](https://github.com/giswqs/label-maker/tree/master/test/fixtures/integration). Note that I did not upload the `sao_tome` folder to GitHub, which includes 420 files and 3 sub-folders. 
`label-maker download --dest sao_tome --config config.intergration.geotiff_package.json`
`label-maker labels --dest sao_tome --config config.intergration.geotiff_package.json`
`label-maker images --dest sao_tome --config config.intergration.geotiff_package.json`

- Run unit test
`python -m unittest test/integration/test_geotiff_package.py `

- Result
``` Saving packaged file to integration-od/sao_tome/data.npz
.
----------------------------------------------------------------------
Ran 1 test in 2.781s

OK
```

**Comment by drewbo** [comment]
@giswqs thanks! This is almost there. Because all our tests run automatically on CircleCI, we need to have the images already present. We already have a very small portion of this tif present in the `test/fixtures` folder so if you make the bounding box very small, you can run `label-maker images` and then `label-maker package`. Instead of running `label-maker download` and `label-maker labels`, you can add the `labels.npz`directly (it should be fairly small). Let me know if you need any help with this

**Comment by giswqs** [comment]
@drewbo Thanks for your guidance! I have changed the bounding box (4 tiles with zoom level 20) and added `labels-tif.npz` based on the small `drone.tif`. 'label-maker images' and  `label-maker package` are embedded in the updated script [test/integration/test_geotiff_package.py](https://github.com/giswqs/label-maker/blob/master/test/integration/test_geotiff_package.py). It seems the test has passed CircleCI. I enjoyed learning this cool stuff! Thank you.

**Comment by drewbo** [comment]
Thanks @giswqs!

**Pull request merged**
